### PR TITLE
Add moinmoin 1.9 and 2.0

### PR DESCRIPTION
**Pull request by TimothyGu**
Would be great if you could add these two repos. Thanks!

### CODE REVIEW

**Comment by john-peterson** [comment]
houston we have a problem

	git clone --mirror https://bitbucket.org/thomaswaldmann/moin-1.9
	Cloning into bare repository 'moin-1.9.git'...
	fatal: repository 'https://bitbucket.org/thomaswaldmann/moin-1.9/' not found

	git clone --mirror https://bitbucket.org/thomaswaldmann/moin-2.0
	Cloning into bare repository 'moin-2.0.git'...
	fatal: repository 'https://bitbucket.org/thomaswaldmann/moin-2.0/' not found

**Comment by TimothyGu** [comment]
hm

**Comment by TimothyGu** [comment]
I live in LA BTW ;)

**Comment by john-peterson** [comment]
change it to hg

**Comment by john-peterson** [comment]
cool

**Comment by TimothyGu** [comment]
BitBucket doesn't show what kind of repo it is on the homepage, and yes I saw that it is hg. Would be great if you could fix it.

**Comment by john-peterson** [comment]
make another pull

**Comment by TimothyGu** [comment]
@john-peterson #17

**Comment by john-peterson** [comment]
wanna hangout? https://plus.google.com/hangouts/_/g25heumqsl76dshkyczzdizvlya?authuser=2&hl=en

**Pull request merged**
